### ISSUE TITLE
Why not use default SKOS mapping properties?

### ISSUE THREAD

**Issue by jindrichmynarz** [jneubert/skos-history#24]
Why not use default SKOS mapping properties? I think this question has been probably considered already, but I cannot find it documented.

SKOS already offers [mapping properties](https://www.w3.org/TR/skos-reference/#mapping) that can cover much of the [use cases](https://github.com/jneubert/skos-history/wiki/List-of-Use-Cases) considered by this project.

If a new version of a concept scheme is produced, we can mint a new instance of `skos:ConceptScheme` (possibly linking it to the previous version via `dcterms:replaces`). The unchanged concepts can be directly included in the new concept scheme via `skos:inScheme` (SKOS allows concepts to take part in multiple concept schemes, see [here](https://www.w3.org/TR/skos-reference/#L1101)). If concept labels or other datatype properties are changed, then we can mint a new `skos:Concept` and link it to its previous version via `skos:closeMatch`. If a concept is split, we can link the child concepts via `skos:broadMatch` to their parent. If concepts are merged, we can link the merged concept to them via `skos:narrowMatch`. Same goes for the changes in semantic relations that translate to the appropriate `skos:*Match` properties.

I'd like to know what are the principal downsides of using the default SKOS mapping properties that warrant using a different solution.

**Comment by jneubert** [comment]
Hi Jindřich, great to meet you in the issue queue!

I'll try a short answer first: The main downside of using the SKOS mapping properties is that this would require the use of "versioned" `skos:Concept`s (because the `skos:*Match` properties have these as domain and range) with different URIs. 

Versioned skos:Concepts mean that over time multiple different versions of a concept would be linked to resources - indivdual books or papers in a library collection, posts in a blog or whatever. In order to achieve complete browsing/retrieval results, you would have to do rather complex reasoning, or alternatively reorganize and update possibly large parts of the indexing when a new version of a vocabulary should be used. This is true for other places too, where concepts are referenced: Think of the nightmare of maintaining a mapping to another SKOS vocabulary. 

Furthermore the rules for the reasoning or the updates would not be clear. Changes in KOS normally affect not only one, but multiple concepts. E.g., the introduction of a new concepts affects not only its broader concept, but maybe also the sister concepts, in that it claims a certain "unit of thought", which may have been associated with the previously existing concepts, which in turn may have been used for indexing other resources. It depends on the rules of the institution which applies the concept scheme, if these resources are reviewed again after changes in the concept scheme. Many other types of changes, with different relevance to the "meaning" of a concept, may occur (for STW, some of them [are already tracked](http://zbw.eu/stw/version/9.0/changes/about.en.html), some may be discovered and tracked in the future, while some changes may be trackable only by intellectual work).  

Which brings me to the last point: I'm not aware of any institution regularily maintaing a thesaurus which is willing to afford the additional costs of tracing changes on a concept level by minting new concept identifiers/URIs when their meaning undergoes some change. So skos-history takes the approach of tracking changes "ex post". It compares published versions of a concept scheme (regarding the individual concept URIs as stable over time). The deltas normally comprise clusters of interrelated changes of multiple concepts, and in general skos-history leaves it to the users to evaluate the significance of the changes. (While different change types and all changes to a single concept can be traced (see the [concepts_deltas](http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/concept_deltas.rq) query), the discovery of such coarser-granular change clusters remains an open research issue).

**Comment by jindrichmynarz** [comment]
Versioned `skos:Concept`s would need to be used if datatype properties (`skos:prefLabel`, `skos:notation` etc.) change. If object properties (`skos:broader`, `skos:related` etc.) change, the same instance of `skos:Concept` can be used.

You bring a number of good points supporting your position. For example, the issues associated to indexing by versioned concepts. However, I think the rebuilding the index when a new version of a `skos:ConceptScheme` is adopted is relatively straightforward. The index can then contain both the current version of the concept and its previous versions. You may already use something like [jprante/elasticsearch-analysis-skos](https://github.com/jprante/elasticsearch-analysis-skos) for query expansion, so a similar approach may be adopted for expanding concept versions.

It is true that maintaining a versioned `skos:ConceptScheme` has a large overhead compared to an unversioned `skos:ConceptScheme`. I'll need to study your papers on skos-history in more depth to understand, how it detects the changes especially if multiple concepts are involved.

**Comment by jneubert** [comment]
typo - commits aimed at #25 ...
